[package]
name = "zerium"
version.workspace = true
edition.workspace = true
description = "A video editor with zero limits."
license.workspace = true

[package.metadata.wgsl-analyzer]
edition = "2026_pre"
root = "../../plugins/zerium.builtin"
include = ["../../plugins/zerium.builtin/**/*.wesl"]

[dependencies]
bytemuck = { version = "1.25", features = ["derive"] }
cosmic-text = "0.18.2"
cpal = "0.15"
directories = "5"
evalexpr.workspace = true
ffmpeg-next = { version = "9", default-features = false, features = ["format", "software-resampling", "software-scaling"] }
futures = "0.3"
gpui = { package = "gpui-ce", git = "https://github.com/1Step621/WGPUI", branch = "fix/input-selection-replacement" }
pollster = "0.4"
resvg = "0.47"
rtrb = "0.3"
rust-embed = { version = "8.12", features = ["debug-embed"] }
rust-i18n.workspace = true
semver = "1"
serde.workspace = true
serde_json.workspace = true
sys-locale = "0.3.2"
thiserror.workspace = true
ui = { git = "https://github.com/1Step621/WGPUI-Component", branch = "fix/input-selection-replacement" }
unicode-segmentation = "1.12"
url = "2"
wgpu = { version = "30", default-features = false }
zerium-core.workspace = true
zerium-shader.workspace = true

[dev-dependencies]
gpui = { package = "gpui-ce", git = "https://github.com/1Step621/WGPUI", branch = "fix/input-selection-replacement", features = ["test-support"] }
