[workspace]
members = ["crates/zerium", "crates/zerium-core", "crates/zerium-shader"]
default-members = ["crates/zerium"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.dependencies]
evalexpr = { version = "13.1", features = ["serde"] }
naga = { version = "30", features = ["wgsl-in"] }
rust-i18n = "4.2.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
zerium-core = { path = "crates/zerium-core" }
zerium-shader = { path = "crates/zerium-shader" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
