[package]
name = "zerium"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25", features = ["derive"] }
cpal = "0.15"
cosmic-text = "0.18.2"
directories = "5"
ffmpeg-next = { version = "9", default-features = false, features = ["format", "software-resampling", "software-scaling"] }
gpui = { package = "gpui-ce", git = "https://github.com/1Step621/WGPUI", branch = "fix/input-selection-replacement" }
ui = { git = "https://github.com/1Step621/WGPUI-Component", branch = "fix/input-selection-replacement" }
naga = { version = "30", features = ["wgsl-in"] }
pollster = "0.4"
rtrb = "0.3"
rust-embed = { version = "8.12", features = ["debug-embed"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
semver = "1"
wgpu = { version = "30", default-features = false }

[dev-dependencies]
gpui = { package = "gpui-ce", git = "https://github.com/1Step621/WGPUI", branch = "fix/input-selection-replacement", features = ["test-support"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
