gpui::actions!(
    zerium,
    [
        DeleteSelectedItem,
        CopySelectedItems,
        CutSelectedItems,
        PasteItems,
        TogglePlayback,
        TogglePlaybackInPlace,
        PreviousFrame,
        NextFrame,
        Undo,
        Redo,
        NewProject,
        OpenProject,
        SaveProject,
        SaveProjectAs,
        OpenExportDialog,
        OpenItemPicker,
        OpenEffectPicker
    ]
);
